// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace something.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("something.Models.Faculty", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("group_id"));

                    b.Property<string>("faculty_name")
                        .HasColumnType("text");

                    b.Property<string>("group_name")
                        .HasColumnType("text");

                    b.Property<int>("year_of_admission")
                        .HasColumnType("integer");

                    b.HasKey("group_id");

                    b.ToTable("facultys");
                });

            modelBuilder.Entity("something.Models.Gifted_grant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("grant_name")
                        .HasColumnType("text");

                    b.Property<int>("grant_value")
                        .HasColumnType("integer");

                    b.Property<int>("student_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("gifted_grants");
                });

            modelBuilder.Entity("something.Models.Grade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("Iscredit")
                        .HasColumnType("boolean");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("grade_")
                        .HasColumnType("text");

                    b.Property<int>("lecturer_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("grades");
                });

            modelBuilder.Entity("something.Models.Grant_info", b =>
                {
                    b.Property<int>("grant_name_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("grant_name_id"));

                    b.Property<int>("aspirant_grant_value")
                        .HasColumnType("integer");

                    b.Property<int>("banch_grant_value")
                        .HasColumnType("integer");

                    b.Property<string>("grant_name")
                        .HasColumnType("text");

                    b.Property<int>("master_grant_value")
                        .HasColumnType("integer");

                    b.HasKey("grant_name_id");

                    b.ToTable("grants_info");
                });

            modelBuilder.Entity("something.Models.Lecturer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("department")
                        .HasColumnType("text");

                    b.Property<string>("father_name")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("lecturers");
                });

            modelBuilder.Entity("something.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("degree")
                        .HasColumnType("text");

                    b.Property<string>("father_name")
                        .HasColumnType("text");

                    b.Property<int>("group")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int>("semester")
                        .HasColumnType("integer");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("students");
                });
#pragma warning restore 612, 618
        }
    }
}
